/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author danielh
 */
public class LoginFrame extends javax.swing.JFrame {

	/**
	 * Creates new form LoginFrame
	 */
	public LoginFrame() {
		initComponents();
		this.setLocationRelativeTo(this);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING:
	 * Do NOT modify this code. The content of this method is always regenerated by the
	 * Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        usrImg = new javax.swing.JLabel();
        usrimgBack = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        usrTxt = new javax.swing.JTextField();
        pasTxt = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        salirBtn = new javax.swing.JButton();
        feedbackLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setName("loginframe"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setMaximumSize(new java.awt.Dimension(400, 300));
        background.setMinimumSize(new java.awt.Dimension(400, 300));
        background.setName(""); // NOI18N
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usrImg.setBackground(new java.awt.Color(255, 255, 255));
        usrImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usrImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/head-g9a8220c16_640.png"))); // NOI18N
        usrImg.setToolTipText("");
        usrImg.setFocusable(false);
        usrImg.setInheritsPopupMenu(false);
        usrImg.setName("usricon"); // NOI18N
        background.add(usrImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 300));

        usrimgBack.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout usrimgBackLayout = new javax.swing.GroupLayout(usrimgBack);
        usrimgBack.setLayout(usrimgBackLayout);
        usrimgBackLayout.setHorizontalGroup(
            usrimgBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        usrimgBackLayout.setVerticalGroup(
            usrimgBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        background.add(usrimgBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 300));

        loginPanel.setBackground(new java.awt.Color(153, 204, 255));

        usrTxt.setFont(new java.awt.Font("Source Code Variable", 1, 15)); // NOI18N
        usrTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usrTxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        usrTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usrTxtActionPerformed(evt);
            }
        });

        pasTxt.setFont(new java.awt.Font("Source Code Variable", 1, 15)); // NOI18N
        pasTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pasTxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pasTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasTxtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Source Code Variable", 1, 16)); // NOI18N
        jLabel1.setText("usuario:");

        jLabel2.setFont(new java.awt.Font("Source Code Variable", 1, 16)); // NOI18N
        jLabel2.setText("contraseña:");

        loginBtn.setBackground(new java.awt.Color(0, 102, 255));
        loginBtn.setFont(new java.awt.Font("Source Code Variable", 1, 18)); // NOI18N
        loginBtn.setText("Iniciar sesion");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        salirBtn.setBackground(new java.awt.Color(255, 102, 102));
        salirBtn.setFont(new java.awt.Font("Source Code Variable", 1, 18)); // NOI18N
        salirBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/exit-32x32.png"))); // NOI18N
        salirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBtnActionPerformed(evt);
            }
        });

        feedbackLbl.setFont(new java.awt.Font("Source Code Variable", 1, 18)); // NOI18N
        feedbackLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addContainerGap(125, Short.MAX_VALUE)
                        .addComponent(feedbackLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addContainerGap(113, Short.MAX_VALUE)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addComponent(salirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(loginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(usrTxt)
                                    .addComponent(pasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usrTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(feedbackLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        loginPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {pasTxt, usrTxt});

        background.add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	public static boolean LoggedIn = false;
	
	private void CheckCredentials()
	{
		String Username = usrTxt.getText();
		String Password = String.valueOf(pasTxt.getPassword());
		
		if (Username.equals("usuario"))
		{
			if (Password.equals("contraseña"))
			{
				LoggedIn = true;
				feedbackLbl.setText("Iniciando sesion");
			}
			else
			{
				feedbackLbl.setText("Contraseña incorrecta");
			}
		}
		else
		{
			feedbackLbl.setText("Usuario incorrecto");
		}
		
		if (LoggedIn)
		{
			MainFrame mainFrame = new MainFrame();
			mainFrame.setVisible(true);
			this.dispose();
		}
	}
	
    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
		CheckCredentials();//revisar credenciales de inicio
    }//GEN-LAST:event_loginBtnActionPerformed

    private void usrTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usrTxtActionPerformed
		feedbackLbl.setText("");
		pasTxt.grabFocus();//pasar foco a campo de contraseña en [enter]
    }//GEN-LAST:event_usrTxtActionPerformed

    private void pasTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasTxtActionPerformed
		feedbackLbl.setText("");
		loginBtnActionPerformed(evt);//revisar credenciales de inicio en [enter]
    }//GEN-LAST:event_pasTxtActionPerformed

    private void salirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBtnActionPerformed
		System.exit(0);//salir del programa
    }//GEN-LAST:event_salirBtnActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new LoginFrame().setVisible(true);
			}
		});
		
		
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel feedbackLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPasswordField pasTxt;
    private javax.swing.JButton salirBtn;
    private javax.swing.JLabel usrImg;
    private javax.swing.JTextField usrTxt;
    private javax.swing.JPanel usrimgBack;
    // End of variables declaration//GEN-END:variables
}
